stages:
  - build
  - deploy

build_frontend:
  before_script:
    - cd frontend
  stage: build
  image: node:22-alpine
  script:
    - npm install
    - npm run build
  variables:
    PARCEL_WORKERS: 0
  artifacts:
    paths:
      - frontend/prod/

build_backend:
  before_script:
    - cd backend
  stage: build
  image: node:22-alpine
  script:
    - npm install
  artifacts:
    paths:
      - backend/

deploy_frontend:
  before_script:
    - cd frontend
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cd prod
    - ls
    - echo Writing docker image to registry $CI_REGISTRY_IMAGE
    - /kaniko/executor
        --context "${CI_PROJECT_DIR}/frontend"
        --dockerfile "${CI_PROJECT_DIR}/frontend/dockerfile"
        --destination "${CI_REGISTRY_IMAGE}/frontend:latest"

deploy_backend:
  before_script:
    - cd backend
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo Writing docker image to registry $CI_REGISTRY_IMAGE
    - /kaniko/executor
        --context "${CI_PROJECT_DIR}/backend"
        --dockerfile "${CI_PROJECT_DIR}/backend/dockerfile"
        --destination "${CI_REGISTRY_IMAGE}/backend:latest"