stages:
  - build
  - test
  - deploy

build_job:
  before_script:
    - cd frontend
  stage: build
  image: node:22-alpine
  script:
    - npm install
    - npm run build
  variables:
    PARCEL_WORKERS: 0 
  artifacts:
    paths:
      - prod/

test_job:
  stage: test
  script:
    - echo "Test stage wird ausgeführt"

deploy_job:
  before_script:
    - cd frontend
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cd prod
    - ls
    - echo Writing docker image to registry $CI_REGISTRY_IMAGE
    - /kaniko/executor
        --context "${CI_PROJECT_DIR}"
        --dockerfile "${CI_PROJECT_DIR}/frontend/dockerfile"
        --destination "${CI_REGISTRY_IMAGE}:latest"