stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: node:22-alpine
  script:
    - npm install
    - npm run build
  variables:
    PARCEL_WORKERS: 0 
  artifacts:
    paths:
      - prod/

test_job:
  stage: test
  script:
    - echo "Test stage wird ausgeführt"

deploy_job:
  stage: deploy
  script:
    - echo "Deploy stage wird ausgeführt"