FROM node:18

# Setze das Arbeitsverzeichnis im Container auf /app
WORKDIR /app

COPY backend/package.json backend/package-lock.json ./
RUN npm install --production
COPY backend/src ./src
EXPOSE 10045
CMD ["node", "src/app.js"]