FROM node:18

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production
COPY src ./src

# Der Container sollte auf dem Standard-Node-Port laufen
EXPOSE 3000

CMD ["node", "src/app.js"]